name: Build and Push Docker image to DockerHub
on:
  push:
    branches: 
      - 'main'
jobs:
    push:
        name: Push Docker image to DockerHub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              with:
                repository: ./Yauheni_Kastsevich/08.Docker_compose/task2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

            - name: Build and Push image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: Yauheni_Kastsevich/08.Docker_compose/task2/Dockerfile
                push: true
                tags: my_docker_rep/jsapp:latest
