name: Create cluster using Minikube
on: [push]
jobs:
  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  
        uses: actions/checkout@master
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
      - name: Check kubectl Cluster Info
        run: |
          kubectl cluster-info
          kubectl get nodes
          kubectl get pods -A
          kubectl version
